# Generated by Django 5.1.5 on 2025-02-13 22:42

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[authentication.validators.CPFValidator()], verbose_name='cpf'),
        ),
    ]
