[project]
name = "wallet-management"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.2.4",
    "django-extensions==4.1",
    "django-filter==25.1",
    "django-phonenumber-field[phonenumbers]==8.1.0",
    "django-stubs[compatible-mypy]>=5.2.0",
    "djangorestframework==3.16.0",
    "djangorestframework-simplejwt==5.5.1",
    "djangorestframework-stubs[compatible-mypy]>=3.16.1",
    "drf-spectacular[sidecar]==0.28.0",
    "factory-boy==3.3.3",
    "faker==37.4.2",
    "ipdb==0.13.13",
    "mypy==1.16.1",
    "pre-commit==4.2.0",
    "psycopg2-binary==2.9.10",
    "python-decouple==3.8",
    "ruff==0.12.5",
    "typing-extensions==4.14.1",
    "debugpy==1.8.15"
]
